const images = {
  avatar: require("../images/avatar.webp"),
  yecaubaogia: require("../images/yeucaubaogia.png"),
  traiCayTuoi: require("../images/traiCayTuoi.png"),
  sansangvanchuyen: require("../images/sansangvanchuyen.png"),
  dichvuhaucan: require("../images/dichvuhaucan.png"),
  raucu: require("../images/raucu.png"),
  thitvaca: require("../images/thit&ca.png"),
  banh: require("../images/banh.png"),
  giavi: require("../images/giavi.png"),
  douong: require("../images/douong.png"),
  sua: require("../images/sua.png"),
  banner: require("../images/banner.png"),
  rauSach: require("../images/rauSach.png"),
  dashboard: require("../images/dashboard.png"),
  chuoiHuong: require("../images/chuoiHuong.png"),
  cangu: require("../images/cangu.png"),
  avtAndcccdImg: require("../images/avt&cccdImg.png"),
  cason: require("../images/cason.png"),
  cccdImg: require("../images/cccdImg.png"),
  pseudo: require("../images/pseudo.png"),
  thitsuon: require("../images/thitsuon.png"),
  trung: require("../images/trung.png"),
  bannerShopAcc: require("../images/bannerShopAcc.png"),
  wallpapperDefault: require("../images/wallpapperDefault.png"),
  dauGoiDau: require("../images/daugoidau.jpg"),
  stick: require("../images/stick.jpg"),
  defalutShopAvt:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk6d0xT7511-bDWKn5-ie9NNqI6x_mZ_KlIvYkemPIQoETP5FA7ealetYxOgdRopg8byE&usqp=CAU",
};

export default images;
