const images = {
  avatar: require("../images/avatar.webp"),
  yecaubaogia: require("../images/yeucaubaogia.png"),
  traiCayTuoi: require("../images/traiCayTuoi.png"),
  sansangvanchuyen: require("../images/sansangvanchuyen.png"),
  dichvuhaucan: require("../images/dichvuhaucan.png"),
  raucu: require("../images/raucu.png"),
  thitvaca: require("../images/thit&ca.png"),
  banh: require("../images/banh.png"),
  giavi: require("../images/giavi.png"),
  douong: require("../images/douong.png"),
  sua: require("../images/sua.png"),
  banner: require("../images/banner.png"),
  rauSach: require("../images/rauSach.png"),
  dashboard: require("../images/dashboard.png"),
  chuoiHuong: require("../images/chuoiHuong.png"),
  cangu: require("../images/cangu.png"),
  cason: require("../images/cason.png"),
  pseudo: require("../images/pseudo.png"),
  thitsuon: require("../images/thitsuon.png"),
  trung: require("../images/trung.png"),
  bannerShopAcc: require("../images/bannerShopAcc.png"),
  dauGoiDau: require("../images/daugoidau.jpg"),
};

export default images;
